apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gemma-assistant-api
  namespace: "910004733138"
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: "10"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/startup-cpu-boost: "true"
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 160
      serviceAccountName: 910004733138-compute@developer.gserviceaccount.com
      timeoutSeconds: 900
      containers:
        - image: us-central1-docker.pkg.dev/enterprise-gemma2/enterprise-gemma2/gemma-assistant-api:v17
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: VERTEX_ENDPOINT_URL
              value: https://mg-endpoint-938bfbf2-2bc1-4937-a058-900bc5f31758.us-east1-702117088368.prediction.vertexai.goog/v1/projects/910004733138/locations/us-east1/endpoints/mg-endpoint-938bfbf2-2bc1-4937-a058-900bc5f31758:rawPredict
            - name: PACKAGE_BUCKET
              value: gemma_think
            - name: SERVICE_ACCOUNT_EMAIL
              value: 910004733138-compute@developer.gserviceaccount.com
            - name: GOOGLE_CLOUD_PROJECT
              value: enterprise-gemma2
            - name: VERTEX_IMAGE_REGION
              value: us-central1
            - name: VERTEX_IMAGE_MODEL
              value: imagen-4.0-generate-001
            - name: AUTH_PROVIDER
              value: iap
            - name: ALLOWED_EMAIL_DOMAIN
              value: workzoneos.org
            - name: GOOGLE_MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: GOOGLE_MAPS_API_KEY
                  key: latest
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
          startupProbe:
            failureThreshold: 1
            periodSeconds: 240
            timeoutSeconds: 240
            tcpSocket:
              port: 8080
  traffic:
    - latestRevision: true
      percent: 100
